/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_stock (void);
GtkWidget* create_window_ajouter (void);
GtkWidget* create_window_supprimer (void);
GtkWidget* create_oui (void);
GtkWidget* create_non (void);
GtkWidget* create_window_rechercher (void);
GtkWidget* create_window_rupture (void);
GtkWidget* create_window_gestcapt (void);
GtkWidget* create_window_ajtcapt (void);
GtkWidget* create_window_supcapt (void);
GtkWidget* create_window_affcapt (void);
GtkWidget* create_window_listcapt (void);
GtkWidget* create_window_bienvenue (void);
GtkWidget* create_window_connexion1 (void);
GtkWidget* create_window_admin (void);
GtkWidget* create_window_ajout_succ (void);
GtkWidget* create_window_confirmer_supp (void);
GtkWidget* create_window_confirm_modif (void);
GtkWidget* create_window_inscription1 (void);
GtkWidget* create_window_connexion2 (void);
GtkWidget* create_window_connexion3 (void);
GtkWidget* create_window_connexion4 (void);
GtkWidget* create_window_connexion5 (void);
GtkWidget* create_window_connexion6 (void);
GtkWidget* create_window_affichage_recherche11 (void);
GtkWidget* create_window_dashboard11 (void);
GtkWidget* create_window_affichage_debit (void);
GtkWidget* create_window1med (void);
GtkWidget* create_window2med (void);
GtkWidget* create_window3med (void);
GtkWidget* create_window4med (void);
GtkWidget* create_window_liste_reclamation (void);
GtkWidget* create_window_ajouter_reclamation (void);
GtkWidget* create_window_supprimer_reclamation (void);
GtkWidget* create_window_modifier_reclamation (void);
GtkWidget* create_window_chercher_reclamation (void);
GtkWidget* create_window_plus_reclame (void);
GtkWidget* create_window_modifier (void);
GtkWidget* create_fenetre_ajout (void);
GtkWidget* create_fenetre_afficher (void);
GtkWidget* create_heber_sup (void);
GtkWidget* create_heber_rech (void);
GtkWidget* create_heber_affrech (void);
GtkWidget* create_nbr_de_niveau (void);
